### ISSUE TITLE
Root Docker npm hook scripts permission issues

### ISSUE THREAD

**Issue by ttshivers** [ahmadnassri/action-semantic-release#2]
The action runs as the root user in the container, which causes permission issues for npm hook scripts.

[semantic-release](https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-use-a-npm-build-script-that-requires-the-package-jsons-version) says to use the `prepublishOnly` or `prepack` hooks if you want to run scripts that need the package.json version. Since the main action script is running as root, when the npm hooks are run, it [changes the uid](https://docs.npmjs.com/misc/scripts#user) to `nobody`, causing hooks that need permissions to fail with errors like:
```
npm WARN lifecycle somepackage@1.1.0~prepack: cannot run in wd somepackage@1.1.0 npm run build (wd=/github/workspace)
```

One fix for this might be to have the entrypoint run as the `node` user (which is already present in the docker node images)

**Comment by ahmadnassri** [comment]
just so I can better understand, and repeat in my own wording: the issue occurs when a `prepublish` step exists in `package.json`'s `scripts` property, which, if it's running some other scripts or local files in the repo .. produces permission issues...

**Comment by ttshivers** [comment]
That is correct, but it is not specific to the `prepublish` step. The main issue is that `npm` is run as root because this action's entrypoint is run as root, which uses `semantic-release`, [which calls](https://github.com/semantic-release/npm/blob/1d1bc40fb8a47f3e40cb8c0268b8ca17b2ace95a/lib/publish.js#L24) `npm publish`, which then calls [many lifecycle scripts](https://docs.npmjs.com/misc/scripts) for events like `prepublish`, `prepare`, `prepublishOnly`, `prepack`, `postpack`, etc. Since npm is invoked with root privileges, it changes the uid to `nobody` by default. [The motivation for this](https://stackoverflow.com/a/42170671) is to prevent malicious lifecycle event scripts from having permission to do malicious things when running as root. 

A simple example of this behavior can be done by:
 - Making a simple nodejs app
 - Putting a simple `prepack` script in `package.json` like:
```
// ...
  "scripts": {
    "prepack": "touch test"
  },
// ..
```
 - Run as root: `npm pack`
 - Observe the warning `npm WARN lifecycle somepackage@1.1.0~prepack: cannot run in wd somepackage@1.1.0 touch test (wd=/test)`, and also observe that the `test` file has not been created
 - Run as normal user: `npm pack`, and observe that it works properly



If the entrypoint of the dockerfile is run as any user other than root, `npm` will not change the uid to `nobody` and lifecycle event scripts will be run as that same user.

**Comment by ahmadnassri** [comment]
got it. I understand how npm livecycle scripts work ... just wanted to confirm the issue is specifically with the docker user 👍

**Comment by ahmadnassri** [comment]
unfortunately it seems GitHub Actions [MUST run as root user](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user) ...

![image](https://user-images.githubusercontent.com/183195/91065915-0b772400-e5ff-11ea-956b-3f83e6a7fe10.png)

**Comment by ahmadnassri** [comment]
I'm trying to think of a way around this from within Docker / semantic-release, though it doesn't seem there are many options ... I'll keep thinking .... but in the meantime could you try to set [`unsafe-perm` to true in `.npmrc`](https://docs.npmjs.com/misc/config#unsafe-perm)

if that resolves the issue, then at least that's a quick path forward, and maybe a thread to chase in this action's execution of `semantic-release`

... maybe even a config value in the action's declaration to do this for the user

**Comment by ttshivers** [comment]
Ah, I didn't know actions had to run as root. I found a workaround by setting an env that sets the `unsafe-perm`
```
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - id: release
        name: semantic-release
        uses: ahmadnassri/action-semantic-release@v1
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_unsafe_perm: true
```

**Comment by ahmadnassri** [comment]
excellent! glad to hear that works.
