### ISSUE TITLE
NPM_TOKEN？？Why need it？

### ISSUE THREAD

**Issue by Val-istar-Guo** [ahmadnassri/action-semantic-release#58]

**Comment by ahmadnassri** [comment]
you don't need it unless you want to publish npm packages to an npm registry ... read docs here: https://semantic-release.gitbook.io/semantic-release/usage/ci-configuration#authentication

**Comment by Val-istar-Guo** [comment]
Could i disable it ? Action will throw error when i not set NPM_TOKEN.

**Comment by Val-istar-Guo** [comment]
I find '@semantic-release/npm' is a plugin and enabled by defaulted.....

**Comment by ahmadnassri** [comment]
you can disabled it by providing a `.releaserc` file to customize which plugins are running

see: https://semantic-release.gitbook.io/semantic-release/usage/configuration

see also: https://semantic-release.gitbook.io/semantic-release/usage/plugins#default-plugins
